export enum ENavLinkUrl {
    'dashboard' = '/dashboard',
    'announcement' = '/announcement',
    'auditLog' = '/audit-log',
    'analytic' = '/analytic',
    'map' = '/map',
    'simulator' = '/simulator',
    'device' = '/device',
    'room' = '/room',
    'event' = '/event',
    'scheduler' = '/scheduler',
    'warehouse' = '/warehouse',
    'product' = '/product',
    'order' = '/order',
    'user' = '/user',
    'group' = '/group',
    'customer' = '/customer',
    'tag' = '/tag',
    'policy' = '/policy',
    'license' = '/license',
    'setting' = '/setting',
    'aboutUs' = '/about-us'
}
